const MOOD_KEY='mw_moods_v1';const CHAT_KEY='mw_chat_v1';
function getMoods(){try{return JSON.parse(localStorage.getItem(MOOD_KEY))||[]}catch(e){return[]}}
function saveMoods(a){localStorage.setItem(MOOD_KEY,JSON.stringify(a))}
function renderMoodList(){const u=document.getElementById('moodList');if(!u)return;const a=getMoods();u.innerHTML='';if(!a.length){u.innerHTML='<li class="muted">No moods yet</li>';return}a.forEach(it=>{const l=document.createElement('li');const d=new Date(it.at).toLocaleString();l.innerHTML=`<strong>${it.mood}</strong> <span class='muted'>— ${d}</span><div>${it.note}</div>`;u.appendChild(l)})}
function attachMoodHandlers(){const b=document.getElementById('saveMoodBtn');if(b){renderMoodList();b.addEventListener('click',()=>{const s=document.getElementById('moodSelect');const n=document.getElementById('moodNote');const i={mood:s.value,note:n.value||'',at:new Date().toISOString()};const a=getMoods();a.unshift(i);saveMoods(a);n.value='';renderMoodList()});const c=document.getElementById('clearMoods');if(c)c.addEventListener('click',()=>{if(confirm('Clear all moods?')){saveMoods([]);renderMoodList()}})}}
function getChats(){try{return JSON.parse(localStorage.getItem(CHAT_KEY))||[]}catch(e){return[]}}
function saveChats(a){localStorage.setItem(CHAT_KEY,JSON.stringify(a))}
function renderChats(){const b=document.getElementById('chatBox');if(!b)return;const a=getChats();b.innerHTML='';a.slice(-200).forEach(m=>{const d=document.createElement('div');d.className='msg';d.innerHTML=`<strong>${m.from}</strong>: ${m.text}`;b.appendChild(d)});b.scrollTop=b.scrollHeight}
function attachChatHandlers(){const s=document.getElementById('sendChat');if(!s)return;renderChats();s.addEventListener('click',()=>{const t=document.getElementById('chatInput');if(!t.value.trim())return;const e={from:'You',text:t.value.trim(),at:new Date().toISOString()};const a=getChats();a.push(e);saveChats(a);t.value='';renderChats();setTimeout(()=>{const r={from:'Peer',text:autoReply(),at:new Date().toISOString()};const a=getChats();a.push(r);saveChats(a);renderChats()},700)})}
function autoReply(){const r=["Thanks for sharing — that's brave.","Sending you calm thoughts.","That sounds tough. I'm here.","Take a deep breath with me.","You're doing your best."];return r[Math.floor(Math.random()*r.length)]}
function attachBreathHandler(){const b=document.getElementById('startBreath');const s=document.getElementById('breathStatus');if(!b)return;b.addEventListener('click',async()=>{b.disabled=true;s.textContent='Starting...';for(let i=0;i<4;i++){s.textContent=`Inhale 4s (${i+1}/4)`;await waitSec(4);s.textContent=`Hold 4s (${i+1}/4)`;await waitSec(4);s.textContent=`Exhale 4s (${i+1}/4)`;await waitSec(4)}s.textContent='Done!';b.disabled=false})}
function waitSec(s){return new Promise(r=>setTimeout(r,s*1000))}
document.addEventListener('DOMContentLoaded',()=>{attachMoodHandlers();attachChatHandlers();attachBreathHandler()});